In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import pickle
%cd D:\iNeuron

D:\iNeuron


In [3]:
df=pd.read_csv("train.csv")
df_temp = df.copy()
df

sl_no  gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1       0  67.00   Others  91.00   Others  Commerce     58.00   
1        2       0  79.33  Central  78.33   Others   Science     77.48   
2        3       0  65.00  Central  68.00  Central      Arts     64.00   
3        4       0  56.00  Central  52.00  Central   Science     52.00   
4        5       0  85.80  Central  73.60  Central  Commerce     73.30   
..     ...     ...    ...      ...    ...      ...       ...       ...   
210    211       0  80.60   Others  82.00   Others  Commerce     77.60   
211    212       0  58.00   Others  60.00   Others   Science     72.00   
212    213       0  67.00   Others  67.00   Others  Commerce     73.00   
213    214       1  74.00   Others  66.00   Others  Commerce     58.00   
214    215       0  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..         ...    ...      ...            ...    ...         ...       ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 15 columns]

In [4]:
df.drop("sl_no",axis=1,inplace=True)
df

gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p   degree_t  \
0         0  67.00   Others  91.00   Others  Commerce     58.00   Sci&Tech   
1         0  79.33  Central  78.33   Others   Science     77.48   Sci&Tech   
2         0  65.00  Central  68.00  Central      Arts     64.00  Comm&Mgmt   
3         0  56.00  Central  52.00  Central   Science     52.00   Sci&Tech   
4         0  85.80  Central  73.60  Central  Commerce     73.30  Comm&Mgmt   
..      ...    ...      ...    ...      ...       ...       ...        ...   
210       0  80.60   Others  82.00   Others  Commerce     77.60  Comm&Mgmt   
211       0  58.00   Others  60.00   Others   Science     72.00   Sci&Tech   
212       0  67.00   Others  67.00   Others  Commerce     73.00  Comm&Mgmt   
213       1  74.00   Others  66.00   Others  Commerce     58.00  Comm&Mgmt   
214       0  62.00  Central  58.00   Others   Science     53.00  Comm&Mgmt   

    workex  etest_p specialisation  mba_p      status    salary  
0       No     55.0         Mkt&HR  58.80      Placed  270000.0  
1      Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2       No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3       No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4       No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..     ...      ...            ...    ...         ...       ...  
210     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 14 columns]

In [5]:
df.isnull().sum()

gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split 
train, test = train_test_split(df, test_size= 0.2, random_state=0)
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
impute = imp_mean.fit_transform(train[['salary']])
train.drop("salary",axis=1,inplace=True)
train['salary'] = impute
impute = imp_mean.transform(test[['salary']])
test.drop("salary",axis=1,inplace=True)
test['salary'] = impute
df = train.append(test)
df = df.round(0)
df

gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p   degree_t  \
16        0   63.0  Central   66.0  Central  Commerce      66.0  Comm&Mgmt   
135       1   72.0  Central   56.0   Others   Science      69.0  Comm&Mgmt   
122       1   66.0  Central   67.0  Central      Arts      69.0  Comm&Mgmt   
22        1   70.0   Others   61.0   Others   Science      72.0   Sci&Tech   
80        1   69.0   Others   62.0   Others  Commerce      69.0  Comm&Mgmt   
..      ...    ...      ...    ...      ...       ...       ...        ...   
90        1   85.0   Others   90.0   Others  Commerce      82.0  Comm&Mgmt   
211       0   58.0   Others   60.0   Others   Science      72.0   Sci&Tech   
106       0   61.0   Others   50.0   Others   Science      54.0   Sci&Tech   
181       0   62.0  Central   60.0   Others   Science      64.0   Sci&Tech   
139       0   77.0  Central   70.0  Central  Commerce      59.0  Comm&Mgmt   

    workex  etest_p specialisation  mba_p      status    salary  
16     Yes     60.0        Mkt&Fin   63.0      Placed  300000.0  
135     No     56.0         Mkt&HR   66.0      Placed  200000.0  
122    Yes     80.0        Mkt&Fin   71.0      Placed  236000.0  
22      No     56.0         Mkt&HR   69.0      Placed  360000.0  
80     Yes     67.0         Mkt&HR   62.0      Placed  240000.0  
..     ...      ...            ...    ...         ...       ...  
90      No     92.0        Mkt&Fin   68.0      Placed  300000.0  
211     No     74.0        Mkt&Fin   54.0      Placed  275000.0  
106     No     71.0        Mkt&Fin   66.0  Not Placed  293306.0  
181     No     63.0         Mkt&HR   60.0  Not Placed  293306.0  
139    Yes     58.0        Mkt&Fin   54.0      Placed  220000.0  

[215 rows x 14 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
df = df.apply(LabelEncoder().fit_transform)
#df.to_csv('final.csv',index=False)

In [ ]:
df1=pd.DataFrame()
df1["ssc_b"]=df_temp["ssc_b"]
df1["ssc_b_Encoded"]=df["ssc_b"]
df1=df1.drop_duplicates("ssc_b")
df1

In [ ]:
df1=pd.DataFrame()
df1["hsc_b"]=df_temp["hsc_b"]
df1["hsc_b_Encoded"]=df["hsc_b"]
df1=df1.drop_duplicates("hsc_b")
df1

In [8]:
df2=pd.DataFrame()
df2["workex"]=df_temp["workex"]
df2["workex_Encoded"]=df["workex"]
df2=df2.drop_duplicates("workex")
df2

workex  workex_Encoded
0     No               0
1    Yes               1

In [9]:
df1=pd.DataFrame()
df1["specialisation"]=df_temp["specialisation"]
df1["specialisation_Encoded"]=df["specialisation"]
df1=df1.drop_duplicates("specialisation")
df1

specialisation  specialisation_Encoded
0         Mkt&HR                       1
1        Mkt&Fin                       0

In [10]:
df1=pd.DataFrame()
df1["hsc_s"]=df_temp["hsc_s"]
df1["hsc_s_Encoded"]=df["hsc_s"]
df1=df1.drop_duplicates("hsc_s")
df1

hsc_s  hsc_s_Encoded
0  Commerce              1
1   Science              2
2      Arts              0

In [11]:
df1=pd.DataFrame()
df1["degree_t"]=df_temp["degree_t"]
df1["degree_t_Encoded"]=df["degree_t"]
df1=df1.drop_duplicates("degree_t")
df1

degree_t  degree_t_Encoded
0    Sci&Tech                 2
2   Comm&Mgmt                 0
34     Others                 1

In [12]:
df1=pd.DataFrame()
df1["status"]=df_temp["status"]
df1["status_Encoded"]=df["status"]
df1=df1.drop_duplicates("status")
df1

status  status_Encoded
0      Placed               1
3  Not Placed               0

In [13]:
df1=pd.DataFrame()
df1["salary"]=df_temp["salary"]
df1["salary"]=df["salary"]
df1=df1.drop_duplicates("salary")
df1

salary
0        19
1         0
2        12
3        27
4        40
7        13
8         8
10       15
13        4
16       29
19       10
20       17
21       36
22       34
26       11
28       33
32       22
37       30
39       38
40       25
47        1
53       41
54        3
55        5
58       18
66       20
74       31
76        7
77       42
85       37
88        2
95       39
101      35
113      23
118      21
119      45
137       6
146       9
150      44
153      32
156      14
162      24
171      26
177      43
191      16
212      28

In [213]:
X = df.drop('status', axis=1) 
Y = df['status'].copy()
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size= 0.2, random_state=0)
pre = np.asarray(x_train.iloc[0])

# **LogisticRegression**

In [190]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(max_iter=800,solver='lbfgs')
clf.fit(x_train, y_train)
pickle.dump(clf,open('log_model.pkl','wb'))
print("Train set mean Accuracy:",clf.score(x_train,y_train))
print("Test set mean Accuracy:",clf.score(x_test,y_test))

Train set mean Accuracy: 0.9127906976744186
Test set mean Accuracy: 0.8604651162790697


In [177]:
y_pred_clf = clf.predict(x_test)
print("Accuracy: \n", accuracy_score(y_test, y_pred_clf))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_clf))
print("Classification Report: \n", classification_report(y_test, y_pred_clf))

Accuracy: 
 0.8604651162790697
Confusion Matrix: 
 [[ 9  4]
 [ 2 28]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.82      0.69      0.75        13
           1       0.88      0.93      0.90        30

    accuracy                           0.86        43
   macro avg       0.85      0.81      0.83        43
weighted avg       0.86      0.86      0.86        43



# **Support Vector Machine Classifier**

In [195]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(C=1.0, gamma='auto'))
clf.fit(x_train, y_train)
pickle.dump(clf,open('svm_model.pkl','wb'))
print("Train set mean Accuracy:",clf.score(x_train,y_train))
print("Test set mean Accuracy:",clf.score(x_test,y_test))

Train set mean Accuracy: 0.9767441860465116
Test set mean Accuracy: 0.9069767441860465


In [179]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
y_pred_clf = clf.predict(x_test)
print("Accuracy: \n", accuracy_score(y_test, y_pred_clf))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_clf))
print("Classification Report: \n", classification_report(y_test, y_pred_clf))

Accuracy: 
 0.9069767441860465
Confusion Matrix: 
 [[10  3]
 [ 1 29]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.77      0.83        13
           1       0.91      0.97      0.94        30

    accuracy                           0.91        43
   macro avg       0.91      0.87      0.88        43
weighted avg       0.91      0.91      0.90        43



# **AdaBoostClassifier (Best)**

In [202]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(x_train, y_train)
pickle.dump(clf,open('adaboost_model.pkl','wb'))
print("Train set mean Accuracy:",clf.score(x_train,y_train))
print("Test set mean Accuracy:",clf.score(x_test,y_test))

Train set mean Accuracy: 1.0
Test set mean Accuracy: 0.9767441860465116


In [221]:
#test = [pre]
pre = np.asarray(x_train.iloc[10])
y_pred = clf.predict([pre])
y_pred
pre

array([  1,  74,   1,  66,   1,   1,  83,   0,   1,  80,   0, 177,   0],
      dtype=int64)

In [181]:
y_pred_clf = clf.predict(x_test)
print("Accuracy: \n", accuracy_score(y_test, y_pred_clf))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_clf))
print("Classification Report: \n", classification_report(y_test, y_pred_clf))

Accuracy: 
 0.9767441860465116
Confusion Matrix: 
 [[13  0]
 [ 1 29]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.97      0.98        30

    accuracy                           0.98        43
   macro avg       0.96      0.98      0.97        43
weighted avg       0.98      0.98      0.98        43



# **SGDClassifier**

In [182]:
from sklearn.linear_model import SGDClassifier
clf = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3)) #SGDClassifier(max_iter=1000, tol=1e-3)
clf.fit(x_train, y_train)
print("Train set mean Accuracy:",clf.score(x_train,y_train))
print("Test set mean Accuracy:",clf.score(x_test,y_test))

Train set mean Accuracy: 0.9069767441860465
Test set mean Accuracy: 0.7674418604651163


In [183]:
y_pred_clf = clf.predict(x_test)
print("Accuracy: \n", accuracy_score(y_test, y_pred_clf))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_clf))
print("Classification Report: \n", classification_report(y_test, y_pred_clf))

Accuracy: 
 0.7674418604651163
Confusion Matrix: 
 [[ 8  5]
 [ 5 25]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.62      0.62      0.62        13
           1       0.83      0.83      0.83        30

    accuracy                           0.77        43
   macro avg       0.72      0.72      0.72        43
weighted avg       0.77      0.77      0.77        43



# **DecisionTreeClassifier**

In [184]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=42)
clf.fit(x_train, y_train)
print("Train set mean Accuracy:",clf.score(x_train,y_train))
print("Test set mean Accuracy:",clf.score(x_test,y_test))

Train set mean Accuracy: 1.0
Test set mean Accuracy: 0.9767441860465116


In [185]:
y_pred_clf = clf.predict(x_test)
print("Accuracy: \n", accuracy_score(y_test, y_pred_clf))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_clf))
print("Classification Report: \n", classification_report(y_test, y_pred_clf))

Accuracy: 
 0.9767441860465116
Confusion Matrix: 
 [[13  0]
 [ 1 29]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.97      0.98        30

    accuracy                           0.98        43
   macro avg       0.96      0.98      0.97        43
weighted avg       0.98      0.98      0.98        43



# **KNeighborsClassifier**

In [186]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train, y_train)
print("Train set mean Accuracy:",clf.score(x_train,y_train))
print("Test set mean Accuracy:",clf.score(x_test,y_test))

Train set mean Accuracy: 0.9534883720930233
Test set mean Accuracy: 0.9069767441860465


In [187]:
y_pred_clf = clf.predict(x_test)
print("Accuracy: \n", accuracy_score(y_test, y_pred_clf))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_clf))
print("Classification Report: \n", classification_report(y_test, y_pred_clf))

Accuracy: 
 0.9069767441860465
Confusion Matrix: 
 [[10  3]
 [ 1 29]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.77      0.83        13
           1       0.91      0.97      0.94        30

    accuracy                           0.91        43
   macro avg       0.91      0.87      0.88        43
weighted avg       0.91      0.91      0.90        43

